name: Continuous Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar y compilar
        run: |
          cd ~/services/PocketGo
          git checkout prod
          git pull origin prod
          docker compose up -d --build